
baseURL = "https://research.ukhsa.gov.uk/"
languageCode = "en-us"
title = "UK Health Security Agency"
theme = "phe"

[menu]

  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 1

  # Parent item
  [[menu.main]]
    name = "Our Research"
    identifier = "our-research"
    url = "/our-research/"
    weight = 2

  # Dropdown items
  [[menu.main]]
    name = "Animal Research"
    parent = "our-research"
    url = "/animal-research/"
    weight = 1

  [[menu.main]]
    name = "Research Integrity"
    parent = "our-research"
    url = "/research-integrity/"
    weight = 2

  # Top-level items
  [[menu.main]]
    name = "Partnerships"
    url = "/partnerships/"
    weight = 3

  [[menu.main]]
    name = "Research Opportunities"
    url = "/opportunities/"
    weight = 4

  [[menu.main]]
    name = "Research Impact"
    url = "/research-impact/"
    weight = 5

  [[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 6

